config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {sessions: 'admins/sessions'}
  devise_for :users, controllers: {sessions: 'users/sessions'}
  get 'order_details/new'

  get 'order_details/show'

  get 'order_details/destroy'

  get 'payment/send'

  get 'payment/receive'

  resources :posts do
    resources :comments
  end
  root 'posts#index'
  get '/jorge',to:'posts#new'

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates_presence_of :title, :message=>"El campo esta vacio"
      validates_length_of :body, :in=> 10..400,:message=>"longitud no valida"
      belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index


   
      if admin_signed_in?
        authenticate_admin!
        @posts = Post.all
       
      else
        authenticate_user!
        @posts = current_user.posts
        
      end
    
=begin
    if user_signed_in?  
     @posts = current_user.posts
     

   else
     if   admin_signed_in?
       @posts = Post.all
     else
      flash[:alert]="jnjkevn"
      redirect_to user_session_path
    end


  else
    flash[:alert]="Necesitas loguearte"
    redirect_to admin_session_path
  end
=end

end
 
  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new

    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id=current_user.id

    respond_to do |format|
      if @post.save
        flash[:success]="Se guardo correctamente el post"
        format.html { redirect_to @post }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        flash[:warning]="No se guardo correctamente"
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        flash[:success]="Se actualizo correctamente el post"
        format.html { redirect_to @post }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        flash[:warning]="No se actualizo correctamente"
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      flash[:success]="Se elimino correctamente el post"
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
  end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <section class="row">
  <div class="small-4 columns">
    <div class="actions">
      <%= f.submit'Aceptar',:class =>'button small success radius'%>
    </div>
  </div>
</section>
 
<% end %>

app/views/posts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
	<ul class="title-area">
		<li class="name">
			<h1><a href="../">Post</a></h1>
		</li>
	</ul>
	<section class="top-bar-section">
		<ul class="left">
			<li class="has-dropdown not-click"><a href="#">Menu</a>
				<ul class="dropdown">
					<li class="title back js-generated" href="#">
						<h5>
							<a href="javascript:void(0)">Back</a>
						</h5>
					</li>
					<li class="parent-link show-for-small-only">
						<a class="parent-link js-generated" href="#">Inicio</a>
					</li>
					<li>
						<label>Menu</label>
					</li>
					
					

					<% if admin_signed_in? %>
					<li><%= link_to'Ver',controller:'/posts',action:'index'%></li>
					<% end %>

					<% if user_signed_in? %>
					<li><%= link_to'Ver',controller:'/posts',action:'index'%></li>
					<li><%= link_to'Nuevo',controller:'/posts',action:'new'%></li>
					<% end %>					
				</ul>
			</li>
			<li class="divider"></li>
		</ul>
		<ul class="right">
			<% if user_signed_in?%>
			<li><a>Logged as <strong><%=current_user.email%></strong>.</a></li>
			<li><%=link_to 'Edit Profile', edit_user_registration_path, :class=>'navbar-link'%></li>
			<li><%=link_to "Logout", destroy_user_session_path, method: :delete, :class=>'navbar-link'%></li>
			<%end%>


			<% if admin_signed_in?%>
			<li><a>Logged ini as <strong><%=current_admin.email%></strong>.</a></li>
			<li><%=link_to 'Edit Profile', edit_admin_registration_path, :class=>'navbar-link'%></li>
			<li><%=link_to "Logout", destroy_admin_session_path, method: :delete, :class=>'navbar-link'%></li>

			<%end%>

			<% if !admin_signed_in? && !user_signed_in? %>
			
			<li><a><%=link_to "Sign up", new_user_registration_path,:class=>'navbar-link'%></a></li>
			<li><%=link_to "Login", new_user_session_path,:class=>'navbar-link'%></li>
			<%end%>


			
		</ul>
	</section>
</nav>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>

<table class="magines">
  <thead>
    <tr>

      
      <th>Title</th>
      <th>Body</th>
       <% if admin_signed_in? %> 
        <th>Author</th>
         <% end %>
              <th colspan="3"></th>
     

         </tr>
  </thead>

  <tbody>
    
    <% @posts.each do |post| %>
    
      <tr>
      
        <td ><%= post.title %></td>
        <td  >
          <% if post.body %>
          <a href="#" data-reveal-id="asesoria-<%= post.id %>">Ver post</a>
          <div id="asesoria-<%= post.id %>"class="reveal-modal"data-reveal  >
            <%=post.body %>
            <a class="close-reveal-modal">&#215;</a>
          </div>
          <% end %>
            </td>
           <% if admin_signed_in? %>
            <td><%=User.find(post.user_id).email%></td>
          <%end%>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
   
  


    

<br>
<% if admin_signed_in? %>
<% end %>

<% if user_signed_in? %>
<%= link_to 'New Post', new_post_path, :class => 'links' %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<div id="comments">
	<%= render :partial =>@post.comments.reverse %>
</div>

<%= form_for([@post,Comment.new],remote:true)do |f|%>
<p><%= f.label :body,"New comment"%><br/>
	<%= f.text_area :body %>
</p>
<section class="row">
  <div class="small-8 columns">
    <div class="actions">
      <%= f.submit'Add comment',:class =>'button small radius'%>
    </div>
  </div>
</section>
<%end%>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>